// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNVDXj3ShLK1tnbDRbkRQIHqSn59tlzAU',
    appId: '1:461304931095:web:f3dd22647c615f4a8a8d52',
    messagingSenderId: '461304931095',
    projectId: 'uniridex',
    authDomain: 'uniridex.firebaseapp.com',
    storageBucket: 'uniridex.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLlB3oKwqENsQD7HqkYKL8ydHvzjFgS-w',
    appId: '1:461304931095:android:e3ebdcdf133f13de8a8d52',
    messagingSenderId: '461304931095',
    projectId: 'uniridex',
    storageBucket: 'uniridex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJVPXybWfYULMcX-GlPKjjjrCHWafyM8Q',
    appId: '1:461304931095:ios:7853e7452ab008368a8d52',
    messagingSenderId: '461304931095',
    projectId: 'uniridex',
    storageBucket: 'uniridex.firebasestorage.app',
    iosClientId: '461304931095-q732dh4o83lnrn375f41ih3eoialt1f5.apps.googleusercontent.com',
    iosBundleId: 'com.uniridex.uniridex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJVPXybWfYULMcX-GlPKjjjrCHWafyM8Q',
    appId: '1:461304931095:ios:7853e7452ab008368a8d52',
    messagingSenderId: '461304931095',
    projectId: 'uniridex',
    storageBucket: 'uniridex.firebasestorage.app',
    iosClientId: '461304931095-q732dh4o83lnrn375f41ih3eoialt1f5.apps.googleusercontent.com',
    iosBundleId: 'com.uniridex.uniridex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNVDXj3ShLK1tnbDRbkRQIHqSn59tlzAU',
    appId: '1:461304931095:web:7ff2a518e25996e78a8d52',
    messagingSenderId: '461304931095',
    projectId: 'uniridex',
    authDomain: 'uniridex.firebaseapp.com',
    storageBucket: 'uniridex.firebasestorage.app',
  );
}
